---
- name: Launch MDB
  hosts: db
  become: true
  
  tasks:
  - name: Install MDB
    package:
      name: mariadb-server
      state: present
      
  - name: Install python3
    dnf:
      name: python3
      state: present  
    
  - name: Install pip3
    package:
        name: python3-pip
        state: present

  - name: Install PyMySQL
    pip:
      name: pymysql
      state: present

  - name: Launch MDB
    service:
      name: mariadb
      enabled: true
      state: started

  - name: Setup root
    mysql_user:
      name: root
      host: localhost
      password: root
      login_unix_socket: /var/lib/mysql/mysql.sock
      login_password: ''
      check_implicit_admin: true
      priv: '*.*:ALL,GRANT'
      state: present

  - name: Setup DB
    mysql_db:
      name: tp1_db
      state: present
      login_user: root
      login_password: root
      
  - name: Setup db user
    mysql_user:
      name: tp1_dbuser
      password: tp1_password
      priv: "tp1_db.*:ALL"
      state: present
      login_user: root
      login_password: root

  - name: Reload MariaDB
    service:
      name: mariadb
      state: restarted